name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - pinned
          - pinned-win
          - stable
          - beta
          - nightly
          - macos
          - win-msvc
        include:
          - build: pinned
            os: ubuntu-22.04
            rust: 1.87.0
          - build: pinned-win
            os: windows-2022
            rust: 1.87.0
          - build: stable
            os: ubuntu-22.04
            rust: stable
          - build: beta
            os: ubuntu-22.04
            rust: beta
          - build: nightly
            os: ubuntu-22.04
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
          - build: win-msvc
            os: windows-2022
            rust: stable
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: cargo build --verbose
      - run: cargo doc --verbose
      - run: cargo test --verbose -- --test-threads 1

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install stable toolchain with rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-features -- --deny warnings

  publish:
    name: publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs: [clippy, test]
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
